"""костыль author.id

Revision ID: 277a1afe5b4b
Revises: 2ff8a84187e6
Create Date: 2024-05-08 23:16:09.349013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277a1afe5b4b'
down_revision: Union[str, None] = '2ff8a84187e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_author_fkey', 'post', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('post_author_fkey', 'post', 'user', ['author'], ['id'])
    # ### end Alembic commands ###
