"""upd user model

Revision ID: 2ff8a84187e6
Revises: 3a2275b8496a
Create Date: 2024-05-06 21:10:41.780713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff8a84187e6'
down_revision: Union[str, None] = '3a2275b8496a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
