"""update first_name and other fields

Revision ID: 46a183278579
Revises: 9243b8f3d0c7
Create Date: 2024-05-08 17:32:50.962025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a183278579'
down_revision: Union[str, None] = '9243b8f3d0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=200), nullable=True))
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
