"""delete field image from db

Revision ID: 6c3348e11e86
Revises: 45dc04090bbb
Create Date: 2024-05-08 21:00:17.786021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c3348e11e86'
down_revision: Union[str, None] = '45dc04090bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
