"""update message and ptp chat models

Revision ID: 92056a1bbd9d
Revises: ea2109a64643
Create Date: 2024-05-09 01:38:08.098416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92056a1bbd9d'
down_revision: Union[str, None] = 'ea2109a64643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('personal_chat_user_first_fkey', 'personal_chat', type_='foreignkey')
    op.drop_constraint('personal_chat_user_second_fkey', 'personal_chat', type_='foreignkey')
    op.drop_column('personal_chat', 'user_first')
    op.drop_column('personal_chat', 'user_second')
    op.drop_index('trgm_name_idx', table_name='user', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('trgm_name_idx', 'user', ['username'], unique=False, postgresql_using='gist')
    op.add_column('personal_chat', sa.Column('user_second', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('personal_chat', sa.Column('user_first', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('personal_chat_user_second_fkey', 'personal_chat', 'user', ['user_second'], ['id'])
    op.create_foreign_key('personal_chat_user_first_fkey', 'personal_chat', 'user', ['user_first'], ['id'])
    # ### end Alembic commands ###
