"""empty message

Revision ID: 9243b8f3d0c7
Revises: 2ff8a84187e6
Create Date: 2024-05-08 16:40:10.904459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9243b8f3d0c7'
down_revision: Union[str, None] = '2ff8a84187e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_tg_id_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_tg_id_key', 'user', ['tg_id'])
    # ### end Alembic commands ###
