"""update message and personal chat models

Revision ID: 98894bb1d325
Revises: cf7804b06a9d
Create Date: 2024-05-09 12:07:34.657876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98894bb1d325'
down_revision: Union[str, None] = 'cf7804b06a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_from_id', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('text', sa.String(), nullable=False))
    op.add_column('message', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('message', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.drop_constraint('message_user_to_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_user_from_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['user_from_id'], ['id'])
    op.drop_column('message', 'user_from')
    op.drop_column('message', 'user_to')
    op.drop_column('message', 'message')
    op.add_column('personal_chat', sa.Column('user_first_id', sa.Integer(), nullable=False))
    op.add_column('personal_chat', sa.Column('user_second_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'personal_chat', 'user', ['user_first_id'], ['id'])
    op.create_foreign_key(None, 'personal_chat', 'user', ['user_second_id'], ['id'])
    op.add_column('user', sa.Column('avatar_url', sa.String(length=1024), nullable=True))
    op.drop_column('user', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar_url')
    op.drop_constraint(None, 'personal_chat', type_='foreignkey')
    op.drop_constraint(None, 'personal_chat', type_='foreignkey')
    op.drop_column('personal_chat', 'user_second_id')
    op.drop_column('personal_chat', 'user_first_id')
    op.add_column('message', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('user_to', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('user_from', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_user_from_fkey', 'message', 'user', ['user_from'], ['id'])
    op.create_foreign_key('message_user_to_fkey', 'message', 'user', ['user_to'], ['id'])
    op.drop_column('message', 'updated_at')
    op.drop_column('message', 'created_at')
    op.drop_column('message', 'text')
    op.drop_column('message', 'user_from_id')
    # ### end Alembic commands ###
