"""add subscriptions

Revision ID: c8f5de2e7e0f
Revises: 6edb6a03b980
Create Date: 2024-05-09 22:47:07.311868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8f5de2e7e0f'
down_revision: Union[str, None] = '6edb6a03b980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscriptions', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscriptions')
    # ### end Alembic commands ###
